@startuml

!theme plain
left to right direction
skinparam linetype ortho

actor "Admin" as admin

rectangle "WorkHours for WHMCS" {
    usecase "Rozpocznij sesję pracy" as startSession
    usecase "Zakończ sesję pracy" as endSession
    usecase "Rozpocznij przerwę" as startBreak
    usecase "Zakończ przerwę" as endBreak
    usecase "Dodaj nowe zadanie" as addTask
    usecase "Ustaw zadanie wykonywane aktualnie" as setTask

    admin --> startSession
    admin --> endSession
    admin --> startBreak
    admin --> endBreak
    admin --> addTask
    admin --> setTask
}

@enduml